name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Package
      run: |
        mkdir artifacts
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp build/Release/takeout_photos_date_setter.exe artifacts/
        else
          cp build/takeout_photos_date_setter artifacts/
        fi
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: takeout_photos_date_setter-${{ matrix.os }}
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write access for creating releases
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create and Upload Release
      run: |
        mv artifacts/takeout_photos_date_setter-ubuntu-latest/takeout_photos_date_setter artifacts/takeout_photos_date_setter-ubuntu
        mv artifacts/takeout_photos_date_setter-macos-latest/takeout_photos_date_setter artifacts/takeout_photos_date_setter-macos
        mv artifacts/takeout_photos_date_setter-windows-latest/takeout_photos_date_setter.exe artifacts/takeout_photos_date_setter-windows.exe
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Automated release for ${{ github.ref_name }}. Binaries for Ubuntu, macOS, and Windows are attached below." \
          --draft=false \
          --prerelease=false
        gh release upload ${{ github.ref_name }} \
          artifacts/takeout_photos_date_setter-ubuntu \
          artifacts/takeout_photos_date_setter-macos \
          artifacts/takeout_photos_date_setter-windows.exe \
          --repo cklukas/TakeoutDates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}