name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Package
      run: |
        mkdir artifacts
        cp build/google_photos_date_setter${{ matrix.os == 'windows-latest' && '.exe' || '' }} artifacts/
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: google_photos_date_setter-${{ matrix.os }}
        path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/google_photos_date_setter-ubuntu-latest/google_photos_date_setter
          artifacts/google_photos_date_setter-macos-latest/google_photos_date_setter
          artifacts/google_photos_date_setter-windows-latest/google_photos_date_setter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}